version: "3.9"

services:
  db:
    image: postgres:13
    volumes:
      - /data/db:/var/lib/postgresql/data
    env_file: .env
  web:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db