# Generated by Django 4.0.5 on 2022-06-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Заказчики'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиции заказа'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Создан', 'Создан'), ('Собирается', 'Собирается'), ('Доставляется', 'Доставляется'), ('Доставлен', 'Доставлен'), ('Выдан', 'Выдан'), ('Отменён', 'Отменён')], default='Создан', max_length=12, verbose_name='Статус заказа'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='admin_panel_status_9a9b7b_idx'),
        ),
    ]
